<a href="https://colab.research.google.com/github/BarathNirnajan/Hackathon-Habitability_score_of_a_property/blob/master/Habitability_score_of_a_property.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HackerEarth Hackathon


## Habitability score of a property

## Problem Statement
Finding the correct property to live in is a crucial task while moving to a new city/location. An inappropriate property can make our life miserable. Can AI help us find better places?

## Task
You have given a relevant dataset about various properties in the USA. Your task is to identify the habitability score of the property.

# Importing Libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import r2_score

# Importing the datasets

In [3]:
train_dataset = pd.read_csv("train.csv")
test_dataset = pd.read_csv("test.csv")
X = train_dataset.iloc[:, 1:-1].values
y = train_dataset.iloc[:, -1].values
test_data = test_dataset.iloc[:, 1:].values

# Train dataset

In [4]:
train_dataset

Property_ID       Property_Type  Property_Area  Number_of_Windows  \
0          0x21e3           Apartment            106                NaN   
1          0x68d4           Apartment            733                2.0   
2          0x7d81           Apartment            737                4.0   
3          0x7a57           Apartment            900                3.0   
4          0x9409            Bungalow           2238               14.0   
...           ...                 ...            ...                ...   
39494      0x6e26  Single-family home           1120                3.0   
39495      0xa013           Apartment            445                1.0   
39496      0x9721            Bungalow           3780                6.0   
39497      0x7e25  Single-family home           1266                3.0   
39498      0x8cb4  Single-family home           1229                2.0   

       Number_of_Doors       Furnishing  Frequency_of_Powercuts Power_Backup  \
0                    1   Semi_Furnished                     0.0           No   
1                    2      Unfurnished                     1.0           No   
2                    2  Fully Furnished                     0.0           No   
3                    2      Unfurnished                     2.0          Yes   
4                    6  Fully Furnished                     0.0           No   
...                ...              ...                     ...          ...   
39494                2              NaN                     0.0           No   
39495                3  Fully Furnished                     1.0           No   
39496                6      Unfurnished                     0.0          Yes   
39497                1   Semi_Furnished                     0.0           No   
39498                4  Fully Furnished                     0.0           No   

                  Water_Supply  Traffic_Density_Score              Crime_Rate  \
0      Once in a day - Morning                   5.89  Slightly below average   
1      Once in a day - Evening                   4.37      Well below average   
2      Once in a day - Morning                   7.45  Slightly below average   
3      Once in a day - Morning                   6.16      Well above average   
4                     All time                   5.46      Well below average   
...                        ...                    ...                     ...   
39494                 All time                   5.55  Slightly above average   
39495                 All time                   5.70  Slightly above average   
39496         Once in two days                   6.84      Well below average   
39497  Once in a day - Morning                   4.60  Slightly above average   
39498                 All time                   8.29      Well below average   

      Dust_and_Noise  Air_Quality_Index  Neighborhood_Review  \
0             Medium               90.0                 3.86   
1             Medium               96.0                 3.55   
2             Medium              121.0                 3.81   
3             Medium              100.0                 1.34   
4             Medium              116.0                 4.77   
...              ...                ...                  ...   
39494         Medium               80.0                 3.56   
39495         Medium               86.0                 2.93   
39496         Medium              137.0                 3.80   
39497            NaN               88.0                 3.25   
39498           High              132.0                 4.67   

       Habitability_score  
0                   71.98  
1                   71.20  
2                   71.39  
3                   31.46  
4                   93.70  
...                   ...  
39494               73.43  
39495               79.91  
39496               81.44  
39497               71.33  
39498               83.25  

[39499 rows x 15 columns]

#Test Dataset

In [5]:
test_dataset

Property_ID       Property_Type  Property_Area  Number_of_Windows  \
0          0x6e93           Apartment            293                3.0   
1          0x8787           Apartment            586                4.0   
2          0x6c17      Container Home            305                1.0   
3          0x9dbd           Apartment            258                2.0   
4          0xbfde            Bungalow           3031               12.0   
...           ...                 ...            ...                ...   
10495      0x423d           Apartment            961                NaN   
10496      0x78c5      Container Home            282                1.0   
10497       0xbf3              Duplex          27445                NaN   
10498      0x305b  Single-family home           1451                2.0   
10499      0x5cff           Apartment            578                NaN   

       Number_of_Doors       Furnishing  Frequency_of_Powercuts Power_Backup  \
0                    1      Unfurnished                     0.0           No   
1                    1   Semi_Furnished                     0.0           No   
2                    2   Semi_Furnished                     1.0           No   
3                    1   Semi_Furnished                     1.0           No   
4                    4  Fully Furnished                     0.0           No   
...                ...              ...                     ...          ...   
10495                3      Unfurnished                     0.0           No   
10496                2   Semi_Furnished                     3.0          Yes   
10497                2  Fully Furnished                     0.0           No   
10498                3      Unfurnished                     1.0          Yes   
10499                1   Semi_Furnished                     0.0           No   

                  Water_Supply  Traffic_Density_Score              Crime_Rate  \
0      Once in a day - Morning                   7.28      Well above average   
1      Once in a day - Evening                   7.63      Well below average   
2                     All time                   5.39  Slightly above average   
3                     All time                   7.53  Slightly below average   
4                     All time                   8.79      Well above average   
...                        ...                    ...                     ...   
10495  Once in a day - Evening                   5.44  Slightly below average   
10496                 All time                   6.72      Well below average   
10497  Once in a day - Evening                   9.28      Well below average   
10498  Once in a day - Evening                   6.25      Well below average   
10499                 All time                   5.98  Slightly below average   

      Dust_and_Noise  Air_Quality_Index  Neighborhood_Review  
0             Medium              152.0                 2.52  
1             Medium               92.0                 4.16  
2             Medium               90.0                 2.92  
3             Medium              158.0                 3.45  
4               High              186.0                 2.72  
...              ...                ...                  ...  
10495         Medium               94.0                 3.55  
10496         Medium              106.0                 2.90  
10497           High              149.0                 4.02  
10498         Medium              131.0                 3.49  
10499         Medium              112.0                 4.15  

[10500 rows x 14 columns]

# OneHotEncode in the test dataset 

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
test_ct1 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
test_data = np.array(test_ct1.fit_transform(test_data))
test_ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
test_data = np.array(test_ct2.fit_transform(test_data))
test_ct3 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [14])], remainder='passthrough')
test_data = np.array(test_ct3.fit_transform(test_data))
test_ct4 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [17])], remainder='passthrough')
test_data = np.array(test_ct4.fit_transform(test_data))
test_ct5 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [23])], remainder='passthrough')
test_data = np.array(test_ct5.fit_transform(test_data))
test_ct6 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [28])], remainder='passthrough')
test_data = np.array(test_ct6.fit_transform(test_data))


# OneHotEncode in the train dataset 

In [7]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
ct2 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [9])], remainder='passthrough')
X = np.array(ct2.fit_transform(X))
ct3 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [14])], remainder='passthrough')
X = np.array(ct3.fit_transform(X))
ct4 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [17])], remainder='passthrough')
X = np.array(ct4.fit_transform(X))
ct5 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [23])], remainder='passthrough')
X = np.array(ct5.fit_transform(X))
ct6 = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [28])], remainder='passthrough')
X = np.array(ct6.fit_transform(X))

# Taking care of Missing values 

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy="mean")
imputer.fit(X[:, 28:34])
X[:, 28:34] = imputer.transform(X[:, 28:34])

In [9]:
imputer2 = SimpleImputer(missing_values = np.nan, strategy="mean")
imputer2.fit(test_data[:, 28:34])
test_data[:, 28:34] = imputer2.transform(test_data[:, 28:34])

# Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc1 = StandardScaler()
X[:, 28:34] = sc.fit_transform(X[:, 28:34])
test_data[:, 28:34] = sc1.fit_transform(test_data[:, 28:34])

In [11]:
X[0]

array([0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0,
       0.0, 106, 1.8882969723253072e-14, -1.1283333495840067,
       -0.6559358167072328, -0.3810650164418948, -0.5025748031975958,
       0.15568473927605375], dtype=object)

# Spliting the  datasets

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
X_train.shape

(31599, 34)

In [14]:
X_test.shape

(7900, 34)

In [15]:
def evaluation(y, predictions):
    r_squared = r2_score(y, predictions)
    return r_squared

In [16]:
models = pd.DataFrame(columns=["Model","R2 Score"])

#Training the Multiple Linear Regression model

In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [18]:
lnr_y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((lnr_y_pred.reshape(len(lnr_y_pred),1), y_test.reshape(len(y_test),1)),1))
r_squared = evaluation(y_test, lnr_y_pred)

print("-"*30)
print("R2 Score:", r_squared)
new_model_row = {"Model": "Multiple Linear Regression","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[77.83 80.55]
 [86.79 87.16]
 [63.79 69.25]
 ...
 [59.28 72.66]
 [82.33 82.  ]
 [95.13 97.13]]
------------------------------
R2 Score: 0.5820177726095304


# Training the SVR model


In [19]:
from sklearn.svm import SVR
svr_regressor = SVR(kernel = 'rbf')
svr_regressor.fit(X_train, y_train)

SVR()

In [20]:
svr_y_pred = svr_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((svr_y_pred.reshape(len(svr_y_pred),1), y_test.reshape(len(y_test),1)),1))
print("-"*30)
r_squared = evaluation(y_test, svr_y_pred)
print("R2 Score:", r_squared)
new_model_row = {"Model": "SVR","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[76.27 80.55]
 [75.61 87.16]
 [75.95 69.25]
 ...
 [76.11 72.66]
 [74.77 82.  ]
 [77.84 97.13]]
------------------------------
R2 Score: -0.0048487019555059074


# Training the Polynomial Regression model 

In [21]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=2)
X_train_2d = poly_reg.fit_transform(X_train)
X_test_2d = poly_reg.transform(X_test)

lin_reg = LinearRegression()
lin_reg.fit(X_train_2d, y_train)

LinearRegression()

In [22]:
predictions = lin_reg.predict(X_test_2d)
np.set_printoptions(precision=2)
print(np.concatenate((predictions.reshape(len(predictions),1), y_test.reshape(len(y_test),1)),1))
print("-"*30)
r_squared = evaluation(y_test, predictions)
print("R2 Score:", r_squared)
new_model_row = {"Model": "Polynomial Regression","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[78.52 80.55]
 [83.03 87.16]
 [63.82 69.25]
 ...
 [60.37 72.66]
 [87.89 82.  ]
 [80.97 97.13]]
------------------------------
R2 Score: 0.7046216578214551


# Training the Decision Tree Regressin model 

In [23]:
from sklearn.tree import DecisionTreeRegressor
decisiontree_regressor = DecisionTreeRegressor(random_state = 0)
decisiontree_regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [24]:
decitree_y_pred = decisiontree_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((decitree_y_pred.reshape(len(decitree_y_pred),1), y_test.reshape(len(y_test),1)),1))
print("-"*30)
r_squared = evaluation(y_test, decitree_y_pred)
print("R2 Score:", r_squared)
new_model_row = {"Model": "Decision Tree Regression","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[89.59 80.55]
 [82.39 87.16]
 [74.9  69.25]
 ...
 [74.78 72.66]
 [91.5  82.  ]
 [84.64 97.13]]
------------------------------
R2 Score: 0.6633389341587386


# Training the Random Forest Regression model

In [25]:
from sklearn.ensemble import RandomForestRegressor
RandomForest_regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
RandomForest_regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [26]:
RandomForest_y_pred = RandomForest_regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((RandomForest_y_pred.reshape(len(RandomForest_y_pred),1), y_test.reshape(len(y_test),1)),1))

print("-"*30)
r_squared = evaluation(y_test, RandomForest_y_pred)
print("R2 Score:", r_squared)
new_model_row = {"Model": "Random Forest Regression","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[80.67 80.55]
 [85.69 87.16]
 [68.22 69.25]
 ...
 [68.82 72.66]
 [81.26 82.  ]
 [92.96 97.13]]
------------------------------
R2 Score: 0.808465214689801


# Training the Ridge model 

In [27]:
from sklearn.linear_model import LinearRegression, Lasso, Ridge, ElasticNet
ridge = Ridge()
ridge.fit(X_train, y_train)

Ridge()

In [28]:
ridge_y_pred = ridge.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((ridge_y_pred.reshape(len(ridge_y_pred),1), y_test.reshape(len(y_test),1)),1))
print("-"*30)
r_squared = evaluation(y_test, ridge_y_pred)
print("R2 Score:", r_squared)
new_model_row = {"Model": "Ridge","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[77.83 80.55]
 [86.79 87.16]
 [63.79 69.25]
 ...
 [59.28 72.66]
 [82.33 82.  ]
 [95.13 97.13]]
------------------------------
R2 Score: 0.5820200085872065


# Training the Lasso Model

In [29]:
lasso = Lasso()
lasso.fit(X_train, y_train)

Lasso()

In [30]:
lasso_y_pred = lasso.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((lasso_y_pred.reshape(len(lasso_y_pred),1), y_test.reshape(len(y_test),1)),1))
print("-"*30)
r_squared = evaluation(y_test, lasso_y_pred)
print("R2 Score:", r_squared)
new_model_row = {"Model": "Lasso","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[77.78 80.55]
 [83.91 87.16]
 [67.64 69.25]
 ...
 [67.36 72.66]
 [79.97 82.  ]
 [87.72 97.13]]
------------------------------
R2 Score: 0.46440553165167064


# Training the ElasticNet Model

In [31]:
elastic_net = ElasticNet()
elastic_net.fit(X_train, y_train)

ElasticNet()

In [32]:
elastic_y_pred = elastic_net.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((elastic_y_pred.reshape(len(elastic_y_pred),1), y_test.reshape(len(y_test),1)),1))
print("-"*30)
r_squared = evaluation(y_test, elastic_y_pred)
print("R2 Score:", r_squared)
new_model_row = {"Model": "ElasticNet","R2 Score": r_squared}
models = models.append(new_model_row, ignore_index=True)

[[75.56 80.55]
 [80.34 87.16]
 [70.82 69.25]
 ...
 [67.9  72.66]
 [80.43 82.  ]
 [84.25 97.13]]
------------------------------
R2 Score: 0.37051161324318593


In [40]:
from google.colab import data_table
data_table.disable_dataframe_formatter()
models.sort_values(by="R2 Score")


Model  R2 Score
1                         SVR -0.004849
7                  ElasticNet  0.370512
6                       Lasso  0.464406
0  Multiple Linear Regression  0.582018
5                       Ridge  0.582020
3    Decision Tree Regression  0.663339
2       Polynomial Regression  0.704622
4    Random Forest Regression  0.808465

# Predicting the test dataset
Random Forest Regression Model has an high R2 score so that predicting the test dataset's Habitability_score using Random Forest Regression Mode

In [34]:
RandomForest_test_pred = RandomForest_regressor.predict(test_data)

In [35]:
print(RandomForest_test_pred.reshape(len(RandomForest_test_pred),1))

[[29.78]
 [80.27]
 [67.89]
 ...
 [75.19]
 [76.92]
 [80.46]]


In [36]:
predicted_table = pd.DataFrame(columns=["Property_ID", "Habitability_score"])
for i in range(len(RandomForest_test_pred)):
    table = {"Property_ID" : test_dataset["Property_ID"][i],"Habitability_score" : RandomForest_test_pred[i]}
    predicted_table = predicted_table.append(table, ignore_index=True)
# predicted_table.to_csv('Habitability_score_submission.csv')

In [37]:
predicted_table

Property_ID  Habitability_score
0          0x6e93              29.783
1          0x8787              80.266
2          0x6c17              67.887
3          0x9dbd              70.361
4          0xbfde              71.531
...           ...                 ...
10495      0x423d              64.413
10496      0x78c5              84.619
10497       0xbf3              75.190
10498      0x305b              76.917
10499      0x5cff              80.464

[10500 rows x 2 columns]